#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use GingTeam\Command\ExtractCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ExtractCommand());

$application->run();
